version: "3.9"

networks:
  dev_env_network:
    driver: bridge

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile.local
    ports:
      - "8081:5000"
    networks:
      - dev_env_network