# Generated by Django 4.0.4 on 2022-05-04 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucherpool_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
            ],
        ),
    ]
