# Generated by Django 4.0.4 on 2022-05-04 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucherpool_api', '0002_specialoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.CharField(default=0, max_length=300, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
