# Generated by Django 4.0.4 on 2022-05-05 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voucherpool_api', '0004_alter_customer_id_alter_specialoffer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('expiry', models.DateTimeField(null=True)),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='voucherpool_api.customer')),
                ('specialOfferId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voucherpool_api.specialoffer')),
            ],
        ),
    ]
