# Generated by Django 4.0.4 on 2022-05-05 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voucherpool_api', '0005_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='dateConsumed',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='isUsed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='customerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voucherpool_api.customer'),
        ),
    ]
