# Generated by Django 4.0.4 on 2022-05-05 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucherpool_api', '0006_voucher_dateconsumed_voucher_isused_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voucher',
            old_name='customerId',
            new_name='customer',
        ),
    ]
