# Generated by Django 4.0.4 on 2022-05-05 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucherpool_api', '0007_rename_customerid_voucher_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voucher',
            old_name='specialOfferId',
            new_name='specialOffer',
        ),
    ]
