# Generated by Django 4.0.4 on 2022-05-06 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voucherpool_api', '0008_rename_specialofferid_voucher_specialoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='voucherpool_api.customer'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='specialOffer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='voucherpool_api.specialoffer'),
        ),
    ]
