name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: '24cb6ca2-ee59-487e-80c6-ddbbcdd5adba'
          heroku_app_name: 'voucherpool'
          heroku_email: 'sarim.javaid.khan@gmail.com'
          usedocker: true
